### ISSUE TITLE
UI needs to become a bit smoother.

### ISSUE THREAD

**Issue by deadlyunicorn** [deadlyunicorn/the-amazing-social-app#4]
- [x] I don't like the logo so much
- [x] The colors - fonts are kind of pale
- [x] Log in / Sign Up needs to be hidden when user is logged in
- [x] Add info about the user (If they are logged in anonymously or with email, their stored info) => Add all of this on a new page "User page"
- [x] Change the homepage to include some info about the project and maybe those issues/features that are being worked on

**Comment by deadlyunicorn** [comment]
/user should contain info taken from Realm 'app' object?
And..
Actually let's rename /user -> /me
and let's keep /user/[id] for a future feature that searches users and gets info about them

**Comment by deadly-unicorn** [comment]
Make it so that you can search for titles by typing (and get autocomplete) instead of having that list..

**Comment by deadlyunicorn** [comment]
- [x] Deleting anon account has no loading box
